services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onno-subscription-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow